package codeOrchestra.colt.js.plugin.actions.run;

import codeOrchestra.colt.core.plugin.ColtSettings;
import codeOrchestra.colt.core.rpc.model.ColtLauncherType;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.vfs.VirtualFile;

import java.io.File;

/**
 * @author Alexander Eliseyev
 */
public class JsRunWithColtNodeWebkitAction extends JsRunWithColt {

    public JsRunWithColtNodeWebkitAction() {
        myLauncherType = ColtLauncherType.NODE_WEBKIT;
        postfix = " (node-webkit)";
    }

    @Override
    public void actionPerformed(AnActionEvent actionEvent) {
        if("".equals(ColtSettings.getInstance().getNodeWebkitPath())) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Node-webkit path is not specified. Go to Preferences -> COLT", NotificationType.ERROR));
            return;
        }
        String path = mainFilePath;
        if(!(path.endsWith(".html") || path.endsWith(".htm"))) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Main document for node-webkit can be only HTML file.", NotificationType.ERROR));
            return;
        }

        String mainDocumentPath = mainFilePath;
        String mainDocumentName = new File(mainFilePath).getName();

        runWithColt(actionEvent, mainDocumentPath, mainDocumentName, "autogenerated");
    }

}
