package codeOrchestra.colt.js.plugin.actions.run;

import codeOrchestra.colt.core.plugin.ColtSettings;
import codeOrchestra.colt.core.rpc.model.ColtLauncherType;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.vfs.VirtualFile;

/**
 * @author Alexander Eliseyev
 */
public class JsRunWithColtNodeWebkitAction extends JsRunWithColt {

    public JsRunWithColtNodeWebkitAction() {
        myLauncherType = ColtLauncherType.NODE_WEBKIT;
    }

    @Override
    public void actionPerformed(AnActionEvent actionEvent) {
        VirtualFile[] virtualFileArray = (VirtualFile[]) actionEvent.getDataContext().getData("virtualFileArray");

        if (virtualFileArray == null || virtualFileArray[0] == null) {
            throw new IllegalStateException(); // should not happen
        }

        if("".equals(ColtSettings.getInstance().getNodeWebkitPath())) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Node-webkit path is not specified. Go to Preferences -> COLT", NotificationType.ERROR));
            return;
        }
        String path = virtualFileArray[0].getPath().toLowerCase();
        if(!(path.endsWith(".html") || path.endsWith(".htm"))) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Main document for node-webkit can be only HTML file.", NotificationType.ERROR));
            return;
        }

        String mainDocumentPath = virtualFileArray[0].getPath();
        String mainDocumentName = virtualFileArray[0].getName();

        runWithColt(actionEvent, mainDocumentPath, mainDocumentName, "autogenerated");
    }

}
