package codeOrchestra.colt.js.plugin.actions.run;

import codeOrchestra.colt.core.rpc.model.ColtLauncherType;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.vfs.VirtualFile;

import java.io.File;

/**
 * @author Alexander Eliseyev
 */
public class JsRunWithColtNodeAction extends JsRunWithColt {

    public JsRunWithColtNodeAction() {
        myLauncherType = ColtLauncherType.NODE_JS;
        postfix = " (node.js)";
    }

    @Override
    public void actionPerformed(AnActionEvent actionEvent) {
        String path = mainFilePath;
        if(!(path.endsWith(".js"))) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Main document for node.js can be only JS file.", NotificationType.ERROR));
            return;
        }

        String mainDocumentPath = mainFilePath;
        String mainDocumentName = new File(mainFilePath).getName();

        runWithColt(actionEvent, mainDocumentPath, mainDocumentName, "autogenerated");
    }

}
