package codeOrchestra.colt.js.plugin.actions;

import codeOrchestra.colt.core.plugin.icons.Icons;
import codeOrchestra.colt.core.rpc.model.ColtLauncherType;
import codeOrchestra.colt.js.plugin.controller.JsColtPluginController;
import codeOrchestra.colt.js.plugin.run.JsColtConfigurationFactory;
import codeOrchestra.colt.js.plugin.run.JsColtConfigurationType;
import codeOrchestra.colt.js.plugin.run.JsColtRunConfiguration;
import com.intellij.execution.ProgramRunnerUtil;
import com.intellij.execution.RunManager;
import com.intellij.execution.RunManagerEx;
import com.intellij.execution.RunnerAndConfigurationSettings;
import com.intellij.execution.configurations.ConfigurationFactory;
import com.intellij.execution.configurations.ConfigurationType;
import com.intellij.execution.executors.DefaultRunExecutor;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.vfs.VirtualFile;
import utils.FileUtils;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author Alexander Eliseyev
 */
public class JsRunWithColtAction extends AnAction {

    public JsRunWithColtAction() {
    }

    @Override
    public void update(AnActionEvent e) {
        super.update(e);

        e.getPresentation().setIcon(Icons.COLT_ICON_16);

        if (e.getProject() == null) {
            e.getPresentation().setEnabled(false);
        }

        VirtualFile[] virtualFileArray = (VirtualFile[]) e.getDataContext().getData("virtualFileArray");
        if (virtualFileArray != null && virtualFileArray.length == 1 && !virtualFileArray[0].isDirectory()) {
            e.getPresentation().setEnabled(true);
        } else {
            e.getPresentation().setEnabled(false);
        }
    }

    private static final Pattern META_PATTERN = Pattern.compile("<meta[^>]*>");
    private static final Pattern META_NAME = Pattern.compile("name=\"([^\"]+)");
    private static final Pattern META_CONTENT = Pattern.compile("content=\"([^\"]+)");

    @Override
    public void actionPerformed(AnActionEvent actionEvent) {
        VirtualFile[] virtualFileArray = (VirtualFile[]) actionEvent.getDataContext().getData("virtualFileArray");

        if (virtualFileArray == null || virtualFileArray[0] == null) {
            throw new IllegalStateException(); // should not happen
        }

        String path = virtualFileArray[0].getPath().toLowerCase();
        if(!(path.endsWith(".html") || path.endsWith(".htm"))) {
            Notifications.Bus.notify(new Notification("colt.notification", "COLT", "Main document for 'Run With COLT' can be only HTML file.", NotificationType.ERROR));
            return;
        }

        String mainDocumentPath = virtualFileArray[0].getPath();
        String mainDocumentName = virtualFileArray[0].getName();

        String content = FileUtils.read(new File(mainDocumentPath));
        Matcher m = META_PATTERN.matcher(content);
        while(m.find()) {
            String group = m.group(0);
            Matcher matcher = META_NAME.matcher(group);
            if(matcher.find()) {
                String name = matcher.group(1);
                System.out.println("name = " + name);
                if("colt-main-document".equals(name)) {
                    Matcher matcher1 = META_CONTENT.matcher(group);
                    if(matcher1.find()) {
                        mainDocumentPath = File.separator + matcher1.group(1);
                    }
                }
            }
        }
        runWithColt(actionEvent, mainDocumentPath, mainDocumentName, "autogenerated");
    }

    private void runWithColt(AnActionEvent actionEvent, String mainDocumentPath, String mainDocumentName, String runConfigurationName) {
        // 1 - export project
        String projectPath = JsColtPluginController.export(actionEvent.getProject(), mainDocumentName, mainDocumentPath, ColtLauncherType.BROWSER);

        // 0 - check if such configuration already exists
        RunManager runManager = RunManager.getInstance(actionEvent.getProject());
        for (RunnerAndConfigurationSettings runnerAndConfigurationSettings : runManager.getConfigurationSettings(getColtConfigurationType(runManager))) {
            if (runnerAndConfigurationSettings.getName().equals(runConfigurationName)) {
                if (runnerAndConfigurationSettings.getConfiguration() instanceof JsColtRunConfiguration) {
                    ProgramRunnerUtil.executeConfiguration(actionEvent.getProject(), runnerAndConfigurationSettings, DefaultRunExecutor.getRunExecutorInstance());
                    return;
                } else {
                    runWithColt(actionEvent, mainDocumentPath, mainDocumentName, runConfigurationName + " (1)");
                    return;
                }
            }
        }

        // 2 - create a run configuration
        JsColtConfigurationType coltConfigurationType = getColtConfigurationType(runManager);
        if (coltConfigurationType == null) {
            throw new IllegalStateException("Can't locate COLT configuration type");
        }
        JsColtConfigurationFactory coltConfigurationFactory = null;
        for (ConfigurationFactory configurationFactory : coltConfigurationType.getConfigurationFactories()) {
            if (configurationFactory instanceof JsColtConfigurationFactory) {
                coltConfigurationFactory = (JsColtConfigurationFactory) configurationFactory;
                break;
            }
        }
        if (coltConfigurationFactory == null) {
            throw new IllegalStateException("Can't locate COLT configuration factory");
        }
        RunnerAndConfigurationSettings runConfiguration = runManager.createRunConfiguration(runConfigurationName, coltConfigurationFactory);
        JsColtRunConfiguration JsColtRunConfiguration = (JsColtRunConfiguration) runConfiguration.getConfiguration();
        JsColtRunConfiguration.setColtProjectPath(projectPath);
        if (runManager instanceof RunManagerEx) {
            runManager.addConfiguration(runConfiguration, false);
            runManager.setSelectedConfiguration(runConfiguration);
        }

        // 3 - run configuration
        ProgramRunnerUtil.executeConfiguration(actionEvent.getProject(), runConfiguration, DefaultRunExecutor.getRunExecutorInstance());
    }

    private JsColtConfigurationType getColtConfigurationType(RunManager runManager) {
        JsColtConfigurationType coltConfigurationType = null;
        for (ConfigurationType configurationType : runManager.getConfigurationFactories()) {
            if (configurationType instanceof JsColtConfigurationType) {
                coltConfigurationType = (JsColtConfigurationType) configurationType;
                break;
            }
        }
        return coltConfigurationType;
    }

}
